name: Doc Monitor

on:
  schedule:
    # Runs daily at 8:05 AM Los Angeles time (15:05 UTC during PDT)
    - cron: '5 15 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      # Restore previous snapshots so we can detect changes across days
      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: state
          key: doc-monitor-state-${{ github.run_id }}
          restore-keys: |
            doc-monitor-state-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python monitor.py

      # Save updated snapshots for the next run
      - name: Save state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: state
          key: doc-monitor-state-${{ github.run_id }}
