name: Doc Monitor

on:
  schedule:
    - cron: '5 15 * * *'   # daily 08:05 Los Angeles during PDT
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show environment and files
        run: |
          python -V
          ls -la
          echo "----- urls.txt -----"
          cat urls.txt || true

      - name: Run monitor
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euxo pipefail
          python monitor.py
